### ISSUE TITLE
Implement proper interval functionality

### ISSUE THREAD

**Issue by mcamis** [mcamis/drive.vote.driver#3]
The driver app should request `waiting_rides` and submit the current driver `location` at dynamic intervals retrieved from the API. Current this is hard-coded to 5000ms.

**Comment by rawls238** [comment]
what's the reasoning behind implementing this? As well what is the proposed solution? To add some jitter to the 5000ms polling interval?

**Comment by mcamis** [comment]
@rawls238 The interval length is determined server side and is returned as part of the `/driving/status` query.
